version: '3.8'

services:
  web:
    build: .
    container_name: flask_downloader
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./downloads:/app/downloads:rw
    environment:
      - DOWNLOAD_DIR=/app/downloads
      - FLASK_APP=app.py
      - FLASK_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3 