version: '3.8'

services:
  web:
    build: .
    container_name: flask_downloader
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./downloads:/app/downloads:rw
      - ./logs:/app/logs:rw
    environment:
      - DOWNLOAD_DIR=/app/downloads
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - TZ=UTC
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  downloads:
    driver: local
  logs:
    driver: local 